### ISSUE TITLE
duplication breaks during has_one on a has_many polymorphic child

### ISSUE THREAD

**Issue by danielpclark** [danielpclark/PolyBelongsTo#6]
I added a fixture geo_location to address with a has_one relationship I'm getting the following error:

```
ArgumentError: wrong number of arguments (1 for 2)
/home/user/dev/PolyBelongsTo/lib/poly_belongs_to/dup.rb:15:in `pbt_deep_dup_build'
/home/user/.rvm/gems/ruby-2.2.0/gems/activerecord-4.0.13/lib/active_record/relation/delegation.rb:60:in `block in method_missing'
/home/user/.rvm/gems/ruby-2.2.0/gems/activerecord-4.0.13/lib/active_record/associations/collection_proxy.rb:849:in `block in scoping'
/home/user/.rvm/gems/ruby-2.2.0/gems/activerecord-4.0.13/lib/active_record/relation.rb:270:in `scoping'
/home/user/.rvm/gems/ruby-2.2.0/gems/activerecord-4.0.13/lib/active_record/associations/collection_proxy.rb:849:in `scoping'
/home/user/.rvm/gems/ruby-2.2.0/gems/activerecord-4.0.13/lib/active_record/relation/delegation.rb:60:in `method_missing'
/home/user/.rvm/gems/ruby-2.2.0/gems/activerecord-deprecated_finders-1.0.3/lib/active_record/deprecated_finders/collection_proxy.rb:22:in `method_missing'
/home/user/dev/PolyBelongsTo/lib/poly_belongs_to/dup.rb:25:in `block in pbt_deep_dup_build'
/home/user/dev/PolyBelongsTo/lib/poly_belongs_to/dup.rb:17:in `each'
/home/user/dev/PolyBelongsTo/lib/poly_belongs_to/dup.rb:17:in `pbt_deep_dup_build'
/home/user/dev/PolyBelongsTo/lib/poly_belongs_to/dup.rb:39:in `pbt_deep_dup_build'
/home/user/dev/PolyBelongsTo/lib/poly_belongs_to/dup.rb:22:in `block (2 levels) in pbt_deep_dup_build'
/home/user/.rvm/gems/ruby-2.2.0/gems/activerecord-4.0.13/lib/active_record/relation/delegation.rb:13:in `each'
/home/user/.rvm/gems/ruby-2.2.0/gems/activerecord-4.0.13/lib/active_record/relation/delegation.rb:13:in `each'
/home/user/dev/PolyBelongsTo/lib/poly_belongs_to/dup.rb:21:in `block in pbt_deep_dup_build'
/home/user/dev/PolyBelongsTo/lib/poly_belongs_to/dup.rb:17:in `each'
/home/user/dev/PolyBelongsTo/lib/poly_belongs_to/dup.rb:17:in `pbt_deep_dup_build'
/home/user/dev/PolyBelongsTo/lib/poly_belongs_to/dup.rb:39:in `pbt_deep_dup_build'
/home/user/dev/PolyBelongsTo/test/dup_test.rb:31:in `block in <class:DupTest>'
```

I'm working on resolving this issue now.

**Comment by danielpclark** [comment]
I've solved this particular issue.  I'm testing for more edge cases.

**Comment by danielpclark** [comment]
https://github.com/danielpclark/PolyBelongsTo/commit/2548c3b075294f44e5f225fca894fb03209f26b1 is the fix.
